### ISSUE TITLE
invenio-requests: exception on accept

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#239]
Environment: inveniordm.web.cern.ch

# To reproduce:
1) create a community
2) invite a person
3) person tries to accept the invitation
4) below error occurs, invitation is never indexed, nevertheless the user becomes a member

```
[2022-06-02 10:32:11,429] ERROR in app: Exception on /requests/617e3d19-195d-4416-87f9-ecc7886fdb29/actions/accept [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/usr/local/lib/python3.8/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_requests/resources/requests/resource.py", line 138, in execute_action
    item = self.service.execute_action(
  File "/usr/local/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 327, in inner
    res = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_requests/services/requests/service.py", line 234, in execute_action
    raise CannotExecuteActionError(action)
invenio_requests.errors.CannotExecuteActionError: Error for action 'accept': Could not execute the action
```

**Comment by kpsherva** [comment]
closing, stale data from previous deployment on inveniordm caused the issue
