### ISSUE TITLE
REST-API: Requests invalid request-id results to 500 internal server error

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-requests#258]
Package version: [b9416](https://github.com/inveniosoftware/invenio-requests/commit/b0ca643ffbe6426b6a464ca0d8693d68234b9416)

## Describe the bug
Related to [735](https://github.com/inveniosoftware/invenio-communities/issues/735) an [46](https://github.com/inveniosoftware/invenio-users-resources/issues/46)
following the [docs](https://inveniordm.docs.cern.ch/reference/rest_api_requests/#:~:text=Get%20a-,request,-%C2%B6): 
Using Postman:
Providing invalid request id will results to 500 internal server error
- **GET {{baseURL}}/api/requests/{{request_id}}**
- **PUT {{baseURL}}/api/requests/{{request_id}}**
- **POST {{baseURL}}/api/requests/{{request_id}}/actions/accept**
- **POST {{baseURL}}/api/requests/{{request_id}}/actions/cancel**
- **POST {{baseURL}}/api/requests/{{request_id}}/actions/decline**
- **POST {{baseURL}}/api/requests/{{request_id}}/comments**
- **GET {{baseURL}}/api/requests/{{request_id}}/comments/timeline**

## Steps to Reproduce
1. Go to Postman
2. send req from one of the endpoints above with invalid id
3. See 500 error

## Expected behavior
Quit gracefully with an error message

## Screenshots (if applicable)

```console
Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 65, in _coerce
    value = uuid.UUID(value)
  File "/home/samk13/.pyenv/versions/3.9.12/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1719, in _execute_context
    context = constructor(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1116, in _init_compiled
    param = {
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1117, in <dictcomp>
    key: processors[key](compiled_params[key])
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1632, in process
    return impl_processor(process_param(value, dialect))
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 80, in process_bind_param
    value = self._coerce(value)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 68, in _coerce
    value = uuid.UUID(bytes=value)
  File "/home/samk13/.pyenv/versions/3.9.12/lib/python3.9/uuid.py", line 186, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_requests/resources/requests/resource.py", line 98, in read
    item = self.service.read(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_requests/services/requests/service.py", line 138, in read
    request = self.record_cls.get_record(id_)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_records/api.py", line 384, in get_record
    obj = query.one()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2865, in one
    return self._iter().one()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1725, in _execute_context
    self._handle_dbapi_exception(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1719, in _execute_context
    context = constructor(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1116, in _init_compiled
    param = {
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1117, in <dictcomp>
    key: processors[key](compiled_params[key])
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1632, in process
    return impl_processor(process_param(value, dialect))
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 80, in process_bind_param
    value = self._coerce(value)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 68, in _coerce
    value = uuid.UUID(bytes=value)
  File "/home/samk13/.pyenv/versions/3.9.12/lib/python3.9/uuid.py", line 186, in __init__
    raise ValueError('bytes is not a 16-char string')
sqlalchemy.exc.StatementError: (builtins.ValueError) bytes is not a 16-char string
[SQL: SELECT request_metadata.created AS request_metadata_created, request_metadata.updated AS request_metadata_updated, request_metadata.json AS request_metadata_json, request_metadata.version_id AS request_metadata_version_id, request_metadata.id AS request_metadata_id, request_metadata.number AS request_metadata_number, request_metadata.expires_at AS request_metadata_expires_at 
FROM request_metadata 
WHERE request_metadata.id = %(id_1)s AND (request_metadata.json IS NULL) != true]

```

**Comment by Samk13** [comment]
- Sending the request for second time you get 500 err on routes:
POST /api/requests/{{request_id}}/actions/accept  | cancel | decline.

- Sending /api/requests/{{request_id}}/actions/acceptXXX  you get 500 err NoSuchActionError

it seems like errors that have been raised are not excepted.
 it's missing an `error_handlers` in [config](https://github.com/inveniosoftware/invenio-requests/blob/master/invenio_requests/resources/requests/config.py#L55) @zzacharo?
 
```console

Traceback (most recent call last):
  File "/home/samk13/dev/v9/invenio-requests/invenio_requests/customizations/actions.py", line 73, in get_action
    return request.type.available_actions[action_name](request)
KeyError: 'acceptx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/dev/v9/invenio-requests/invenio_requests/resources/requests/resource.py", line 138, in execute_action
    item = self.service.execute_action(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_records_resources/services/uow.py", line 324, in inner
    res = f(self, *args, **kwargs)
  File "/home/samk13/dev/v9/invenio-requests/invenio_requests/services/requests/service.py", line 230, in execute_action
    action_obj = RequestActions.get_action(request, action)
  File "/home/samk13/dev/v9/invenio-requests/invenio_requests/customizations/actions.py", line 75, in get_action
    raise NoSuchActionError(action=action_name)
invenio_requests.errors.NoSuchActionError: Error for action 'acceptx': No such action available
```
